
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  qdrant:
    image: qdrant/qdrant
    ports:
    - "6340:6333" 

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
      - qdrant

      
